// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Aura {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aura.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VideoSizeMessage {
            get {
                return ResourceManager.GetString("VideoSizeMessage", resourceCulture);
            }
        }
        
        internal static string YesBtnLabel {
            get {
                return ResourceManager.GetString("YesBtnLabel", resourceCulture);
            }
        }
        
        internal static string ListVideoStatusMessage {
            get {
                return ResourceManager.GetString("ListVideoStatusMessage", resourceCulture);
            }
        }
        
        internal static string PostBtnLabel {
            get {
                return ResourceManager.GetString("PostBtnLabel", resourceCulture);
            }
        }
        
        internal static string ReportVideoMsgLabel {
            get {
                return ResourceManager.GetString("ReportVideoMsgLabel", resourceCulture);
            }
        }
        
        internal static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        internal static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        internal static string StatusUploadTittle {
            get {
                return ResourceManager.GetString("StatusUploadTittle", resourceCulture);
            }
        }
        
        internal static string PostPageLabel {
            get {
                return ResourceManager.GetString("PostPageLabel", resourceCulture);
            }
        }
        
        internal static string ReportVideoLabel {
            get {
                return ResourceManager.GetString("ReportVideoLabel", resourceCulture);
            }
        }
        
        internal static string LogOutConfLabel {
            get {
                return ResourceManager.GetString("LogOutConfLabel", resourceCulture);
            }
        }
        
        internal static string SOTDLabel {
            get {
                return ResourceManager.GetString("SOTDLabel", resourceCulture);
            }
        }
        
        internal static string GameLabel {
            get {
                return ResourceManager.GetString("GameLabel", resourceCulture);
            }
        }
        
        internal static string ProfilePageLabel {
            get {
                return ResourceManager.GetString("ProfilePageLabel", resourceCulture);
            }
        }
        
        internal static string CommentUploadTittle {
            get {
                return ResourceManager.GetString("CommentUploadTittle", resourceCulture);
            }
        }
        
        internal static string GameMsgLabel {
            get {
                return ResourceManager.GetString("GameMsgLabel", resourceCulture);
            }
        }
        
        internal static string VideoSizeSelectAgainMessage {
            get {
                return ResourceManager.GetString("VideoSizeSelectAgainMessage", resourceCulture);
            }
        }
        
        internal static string CancelBtnLabel {
            get {
                return ResourceManager.GetString("CancelBtnLabel", resourceCulture);
            }
        }
        
        internal static string AskTittle {
            get {
                return ResourceManager.GetString("AskTittle", resourceCulture);
            }
        }
        
        internal static string PopularLabel {
            get {
                return ResourceManager.GetString("PopularLabel", resourceCulture);
            }
        }
        
        internal static string LogOutLabel {
            get {
                return ResourceManager.GetString("LogOutLabel", resourceCulture);
            }
        }
        
        internal static string OkBtnLabel {
            get {
                return ResourceManager.GetString("OkBtnLabel", resourceCulture);
            }
        }
        
        internal static string HomePageLabel {
            get {
                return ResourceManager.GetString("HomePageLabel", resourceCulture);
            }
        }
        
        internal static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        internal static string AskSignLabel {
            get {
                return ResourceManager.GetString("AskSignLabel", resourceCulture);
            }
        }
        
        internal static string LikedLabel {
            get {
                return ResourceManager.GetString("LikedLabel", resourceCulture);
            }
        }
        
        internal static string AskUploadTittle {
            get {
                return ResourceManager.GetString("AskUploadTittle", resourceCulture);
            }
        }
        
        internal static string ReportBtnLabel {
            get {
                return ResourceManager.GetString("ReportBtnLabel", resourceCulture);
            }
        }
        
        internal static string DeleteVideoLabel {
            get {
                return ResourceManager.GetString("DeleteVideoLabel", resourceCulture);
            }
        }
        
        internal static string LikeLabel {
            get {
                return ResourceManager.GetString("LikeLabel", resourceCulture);
            }
        }
        
        internal static string EditPageLabel {
            get {
                return ResourceManager.GetString("EditPageLabel", resourceCulture);
            }
        }
        
        internal static string NoBtnLabel {
            get {
                return ResourceManager.GetString("NoBtnLabel", resourceCulture);
            }
        }
        
        internal static string SettingMsgLabel {
            get {
                return ResourceManager.GetString("SettingMsgLabel", resourceCulture);
            }
        }
        
        internal static string VideoSizeTitle {
            get {
                return ResourceManager.GetString("VideoSizeTitle", resourceCulture);
            }
        }
        
        internal static string DictionaryLabel {
            get {
                return ResourceManager.GetString("DictionaryLabel", resourceCulture);
            }
        }
        
        internal static string DeleteVideoMsgLabel {
            get {
                return ResourceManager.GetString("DeleteVideoMsgLabel", resourceCulture);
            }
        }
        
        internal static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
    }
}
